- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFeralInfected
  name: Feral Infected Role
  components:
  - type: MindRole
    antagPrototype: FeralInfected
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-feral-infected
  - type: FeralInfectedRole
