- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeretic
  name: Heretic Role
  components:
  - type: MindRole
    antagPrototype: Heretic
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-heretic
  - type: HereticRole
